# Generated by Django 6.0.5 on 2026-08-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_online_status',
            field=models.CharField(choices=[('everyone', 'Tout le campus'), ('friends', 'Mes amis'), ('nobody', 'Personne')], default='friends', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='who_can_friend_request',
            field=models.CharField(choices=[('everyone', 'Tout le campus'), ('nobody', 'Personne')], default='everyone', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='who_can_message',
            field=models.CharField(choices=[('everyone', 'Tout le campus'), ('friends', 'Mes amis'), ('nobody', 'Personne')], default='friends', max_length=10),
        ),
    ]
