# Generated by Django 6.0.5 on 2026-08-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_show_online_status_user_who_can_friend_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creator_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
    ]
