# Generated by Django 6.0.5 on 2026-05-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default='general', max_length=100),
        ),
    ]
