# Generated by Django 6.0.5 on 2026-08-15 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_group_groupmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='social.group'),
        ),
        migrations.AddField(
            model_name='group',
            name='filiere',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='group',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='niveau',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='leave_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='role',
            field=models.CharField(choices=[('member', 'Membre'), ('admin', 'Admin')], default='member', max_length=10),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='kind',
            field=models.CharField(choices=[('cycle_licence', 'Cycle Licence'), ('cycle_master', 'Cycle Master'), ('niveau_annonces', 'Annonces de niveau'), ('niveau_discussion', 'Discussion de niveau'), ('club', 'Club / Association'), ('projet', 'Groupe de projet')], default='club', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('friend_request', "Demande d'amitié"), ('friend_accepted', 'Amitié acceptée'), ('message', 'Message'), ('status', 'Statut'), ('announcement', 'Annonce'), ('leave_request', 'Demande de départ')], max_length=20),
        ),
    ]
