# Generated by Django 6.0.5 on 2026-08-15 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_announcement_group_group_filiere_group_is_system_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('kind', 'filiere', 'niveau'), name='unique_system_group'),
        ),
    ]
