# Generated by Django 6.0.5 on 2026-08-17 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_announcement_file_announcement_is_urgent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='social.status')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('status', 'viewer')},
            },
        ),
    ]
